# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 85f5201f904d4359a9a6592a8cfae402e99859a3ea73ecd915b55c4dd298b13532597fe09ea755131b76fb3c0e6a49851a11682e88fdf18338d3f45db1b9e8ff

test:
  domain_name: example.com 
  secret_key_base: 98ffe3243137b05054866ae7253ec72ef79c011906dd00b1aeafefd1d11e3988546a1e26ebb4825ac48cb74e878c0a641b603c882ac8d8fff5ec4d28a3c28e40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
